galaxy_info:
  author: MrCloud
  description: Roles that I use for a macOS setup for iOS or Android development and mobile CI running on macOS
  license: license (MIT)
  min_ansible_version: 2.2

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  platforms:
    - name: MacOSX
      versions:
        - all
        - any
  galaxy_tags:
    - ios
    - ci
    - swift
    - android

dependencies:
  - oh-my-zsh
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
