---
configure_xcode: yes
configure_custom_swift: no
configure_macos_defaults: no
configure_ruby_rbenv: yes
homebrew_upgrade_all_packages: no
use_mac_store: no

xcode_src: Xcode_9.4.1.xip

rbenv_ruby_version: 2.4.3
rbenv_global_gems:
  - bundler
  - xcpretty
  - fastlane

swift_version_custom: 4.1.2

macos_sleep_options:
  - systemsetup -setsleep Never
  - systemsetup -setharddisksleep Never
  - systemsetup -setcomputersleep Never

macos_animation_options:
  - defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
  - defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
  - defaults write com.apple.dock expose-animation-duration -int 0
  - defaults write com.apple.dock launchanim -bool false

macos_software_autoupdates:
  - softwareupdate --schedule off

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
homebrew_repo: https://github.com/Homebrew/brew
homebrew_prefix: /usr/local
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: /usr/local/bin

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - boost
  - carthage
  - cmake
  - git
  - git-flow
  - mint
  - openssl
  - sonar-scanner
  # - sourcery # or cocoapods in projects
  # - swiftformat # in projects, in xcode extension, in git pre-commit hook ?
  # - swiftlint


homebrew_uninstalled_packages:

homebrew_taps:
  - name: homebrew/core
  - name: caskroom/cask
  - name: homebrew/binary
  - name: homebrew/dupes
  - name: homebrew/versions
  - name: caskroom/versions
  - name: facebook/fb
  - name: yonaskolb/Mint
    url: https://github.com/yonaskolb/Mint.git

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - appium

homebrew_cask_ql_plugins:
  - provisionql #iOS ipa and provisionning QuickLook plugin

mas_email: ""
mas_password: ""
mas_installed_app_ids: [] # Don't use this option
mas_installed_apps: []

mas_upgrade_all_apps: no
